export const GET_ERRORS = 'GET_ERRORS';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';

export const GET_BACKLOG = 'GET_BACKLOG';
export const GET_PROJECT_TASK = 'GET_PROJECT_TASK';
export const DELETE_PROJECT_TASK = 'DELETE_PROJECT_TASK';

export const CREATE_PROJECT_TASK_SUCCESS = 'CREATE_PROJECT_TASK_SUCCESS';
export const UPDATE_PROJECT_TASK_SUCCESS = 'UPDATE_PROJECT_TASK_SUCCESS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
