POST http://localhost:8001/api/projects HTTP/1.1
Content-Type: application/json

{   
    "projectName": "test Name",
    "description": "test description",
    "startDate": "2019-02-13",
    "endDate":"2019-02-15"
}


###

POST http://localhost:8001/api/backlog/b1d9d035-feb5-4072-93c7-18d3d426d0f0 HTTP/1.1
Content-Type: application/json

{   
    "summary": "test Name",
    "acceptanceCriteria": "test description",
    "status": "",
    "priority": "1",
    "dueDate":"2019-02-15",
    "projectId": "b1d9d035-feb5-4072-93c7-18d3d426d0f0"
}

###

POST http://localhost:8001/api/projects HTTP/1.1
Content-Type: application/json

{   
    "id": 1,
    "projectName": "Name",
    "description": "test description",
    "startDate":"2020-02-01",
    "endDate":"2020-02-05"
}

###

POST http://localhost:8001/api/projects HTTP/1.1
Content-Type: application/json

{
    "projectName": "test Name2",
    "description": "test description",
    "startDate": "2019-02-13",
    "endDate":"2019-02-15"
}


###

POST http://localhost:8001/api/projects HTTP/1.1
Content-Type: application/json

{
    "projectName": "test Name",
    "startDate":"2020-02-01",
    "endDate":"2020-02-05"
}

###


GET http://localhost:8001/api/projects/test HTTP/1.1

###

GET http://localhost:8001/api/projects/all HTTP/1.1

###

DELETE http://localhost:8001/api/projects/test HTTP/1.1